#!/bin/sh
#
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/dbus/user_bus_socket
export WAYLAND_CLIENT_DIR=/tmp
export WESTON_CONFIG=/etc/xdg/weston/weston-user.ini
#weston --log=$XDG_RUNTIME_DIR/weston.log --backend=wayland-backend.so --width=720 --height=1080 &
weston --log=$XDG_RUNTIME_DIR/weston.log --backend=wayland-backend.so &
xwalk-launcher Modello005.Homescreen
