#!/bin/sh
#
export XDG_RUNTIME_DIR=/run/display
/usr/bin/ln -sf /run/display/wayland-0 /run/user/$UID/
/bin/sh -l -c "/usr/bin/tz-launcher -c /usr/share/applications/tizen/launcher.conf $HOME/.applications/desktop"
